# This is a basic workflow to help you get started with Actions

name: Build on push to main

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:  
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: GitVersion
        id: gitversion
        uses: PoshCode/Actions/gitversion@v1
      - name: Install-RequiredModules
        uses: PoshCode/Actions/install-requiredmodules@v1
      - name: Build Module
        id: build
        uses: PoshCode/actions/build-module@v1
        with:
          version: ${{ steps.gitversion.outputs.LegacySemVerPadded }}
          destination: ${{github.workspace}}/output
