name: Build on push to main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: GitVersion
        id: gitversion
        uses: PoshCode/Actions/gitversion@v1

      - name: Install-RequiredModules
        uses: PoshCode/Actions/install-requiredmodules@v1

      - name: Build Module
        id: build
        uses: PoshCode/actions/build-module@v1
        with:
          version: ${{ steps.gitversion.outputs.LegacySemVerPadded }}
          destination: ${{github.workspace}}/output

      - name: Upload Build Output
        uses: actions/upload-artifact@v2
        with:
          name: Modules
          path: ${{github.workspace}}/output

      # - name: Download required binaries
      #   shell: pwsh
      #   run: ./scripts/downloadDependencies.ps1 -OutputFolder ${{github.workspace}}/Tests

      # - name: Upload Tests
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: PesterTests
      #     path: ${{github.workspace}}/Tests

      - name: Upload RequiredModules.psd1
        uses: actions/upload-artifact@v2
        with:
          name: RequiredModules
          path: ${{github.workspace}}/RequiredModules.psd1

      - name: Upload PSScriptAnalyzerSettings.psd1
        uses: actions/upload-artifact@v2
        with:
          name: ScriptAnalyzer
          path: ${{github.workspace}}/PSScriptAnalyzerSettings.psd1

  # test:
  #   runs-on: windows-latest
  #   needs: build
  #   steps:
  #     - name: Download Build Output
  #       uses: actions/download-artifact@v2
  #     - uses: PoshCode/Actions/install-requiredmodules@v1
  #     - uses: PoshCode/Actions/pester@v1
  #       with:
  #         codeCoveragePath: Modules/BicepDev
  #         moduleUnderTest: BicepDev
  #         additionalModulePaths: ${{github.workspace}}/Modules

  #     - name: Upload Results
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: Pester Results
  #         path: ${{github.workspace}}/*.xml

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() && contains(github.event.head_commit.message, 'PSGalleryPublish') && github.ref == 'refs/heads/master' }}
    steps:
      - name: Download Build Output
        uses: actions/download-artifact@v2
      - name: Publish Module to PowerShell Gallery
        uses: pcgeek86/publish-powershell-module-action@v20
        id: publish-module
        with:
          NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}
          modulePath: Modules/BicepDev
