name: Build on push to main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install-RequiredModules
        uses: PoshCode/Actions/install-requiredmodules@v1

      - name: Download required binaries
        shell: pwsh
        run: ./scripts/downloadDependencies.ps1 -OutputFolder ${{github.workspace}}/Tests

      - name: What is going on here
        shell: pwsh
        run: $Test = ${{github.workspace}}\Tests\bicep.exe build ${{github.workspace}}\Tests\SampleData\Modules\appGateway\deploy.bicep

